from tkinter import *

class Slabel:
    suited = None
    rank1 = None
    rank2 = None
    valid_suit = ['s', 'o', 'p']
    valid_rank = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A']

    def __init__(self, suited, rank1, rank2, frame):
        ''' Initialize the suit and rank of a card

        Args:
            suit: string, suit of the card, should be one of valid_suit
            rank: string, rank of the card, should be one of valid_rank
        '''
        self.suited = suited
        self.rank1 = rank1
        self.rank2 = rank2
        button1 = Label(frame, width=4, height=2, relief="groove")
        if rank1 == rank2:
            button1.config(text=rank1+rank2)
        else:
            for i in self.valid_rank:
                if i == rank1:
                    button1.config(text=rank2+rank1+suited)

        S = 0
        H = 0
        D = 0
        C = 0
        P = []

    def show(self):
        print(self.suited)

    def color(self):




        


def strategy():
    exploiter = Tk()
    exploiter.geometry("1100x520-1300+600")
    exploiter.title("Strategy")
    exploiter.resizable(False,False)

    frame1 = Frame(exploiter, width = 500, height=480, relief=RIDGE)
    frame2 = Frame(exploiter, width = 500, height=480, relief=RIDGE)
    frame3 = Frame(exploiter, width = 100, height=480, relief=RIDGE)
    frame4 = Frame(exploiter, width = 500, height=40, relief=RIDGE)
    frame5 = Frame(exploiter, width = 100, height=40, relief=RIDGE)
    frame6 = Frame(exploiter, width = 500, height=40, relief=RIDGE)

    frame4.grid(row=1,column=1)
    frame5.grid(row=1,column=2)
    frame6.grid(row=1,column=3)
    frame1.grid(row=2,column=1)
    frame3.grid(row=2,column=2)
    frame2.grid(row=2,column=3)

    lab1 = Label(frame4, text="Normal Strategy", relief=RIDGE)
    lab1.pack()
    lab2 = Label(frame6, text="Exploit Strategy", relief=RIDGE)
    lab2.pack()

    labelAA = Label(frame1, width=4, height=2, text="AA", relief="groove")
    labelAKs = Label(frame1, width=4, height=2, text="AKs", relief="groove")
    labelAQs = Label(frame1, width=4, height=2, text="AQs", relief="groove")
    labelAJs = Label(frame1, width=4, height=2, text="AJs", relief="groove")
    labelA10s = Label(frame1, width=4, height=2, text="A10s", relief="groove")
    labelA9s = Label(frame1, width=4, height=2, text="A9s", relief="groove")
    labelA8s = Label(frame1, width=4, height=2, text="A8s", relief="groove")
    labelA7s = Label(frame1, width=4, height=2, text="A7s", relief="groove")
    labelA6s = Label(frame1, width=4, height=2, text="A6s", relief="groove")
    labelA5s = Label(frame1, width=4, height=2, text="A5s", relief="groove")
    labelA4s = Label(frame1, width=4, height=2, text="A4s", relief="groove")
    labelA3s = Label(frame1, width=4, height=2, text="A3s", relief="groove")
    labelA2s = Label(frame1, width=4, height=2, text="A2s", relief="groove")

    labe1 = [labelAA, labelAKs, labelAQs, labelAJs, labelA10s, labelA9s, labelA8s, labelA7s, labelA6s, labelA5s, labelA4s, labelA3s, labelA2s]


    labelAKo = Label(frame1, width=4, height=2, text="AKo", relief="groove")
    labelKK = Label(frame1, width=4, height=2, text="KK", relief="groove")
    labelKQs = Label(frame1, width=4, height=2, text="KQs", relief="groove")
    labelKJs = Label(frame1, width=4, height=2, text="KJs", relief="groove")
    labelK10s = Label(frame1, width=4, height=2, text="K10s", relief="groove")
    labelK9s = Label(frame1, width=4, height=2, text="K9s", relief="groove")
    labelK8s = Label(frame1, width=4, height=2, text="K8s", relief="groove")
    labelK7s = Label(frame1, width=4, height=2, text="K7s", relief="groove")
    labelK6s = Label(frame1, width=4, height=2, text="K6s", relief="groove")
    labelK5s = Label(frame1, width=4, height=2, text="K5s", relief="groove")
    labelK4s = Label(frame1, width=4, height=2, text="K4s", relief="groove")
    labelK3s = Label(frame1, width=4, height=2, text="K3s", relief="groove")
    labelK2s = Label(frame1, width=4, height=2, text="K2s", relief="groove")

    labe2 = [labelAKo, labelKK, labelKQs, labelKJs, labelK10s, labelK9s, labelK8s, labelK7s, labelK6s, labelK5s, labelK4s, labelK3s, labelK2s]

    labelAQo = Label(frame1, width=4, height=2, text="AQo", relief="groove")
    labelKQo = Label(frame1, width=4, height=2, text="KQo", relief="groove")
    labelQQ = Label(frame1, width=4, height=2, text="QQ", relief="groove")
    labelQJs = Label(frame1, width=4, height=2, text="QJs", relief="groove")
    labelQ10s = Label(frame1, width=4, height=2, text="Q10s", relief="groove")
    labelQ9s = Label(frame1, width=4, height=2, text="Q9s", relief="groove")
    labelQ8s = Label(frame1, width=4, height=2, text="Q8s", relief="groove")
    labelQ7s = Label(frame1, width=4, height=2, text="Q7s", relief="groove")
    labelQ6s = Label(frame1, width=4, height=2, text="Q6s", relief="groove")
    labelQ5s = Label(frame1, width=4, height=2, text="Q5s", relief="groove")
    labelQ4s = Label(frame1, width=4, height=2, text="Q4s", relief="groove")
    labelQ3s = Label(frame1, width=4, height=2, text="Q3s", relief="groove")
    labelQ2s = Label(frame1, width=4, height=2, text="Q2s", relief="groove")

    labe3 = [labelAQo, labelKQo, labelQQ, labelQJs, labelQ10s, labelQ9s, labelQ8s, labelQ7s, labelQ6s, labelQ5s, labelQ4s, labelQ3s, labelQ2s]

    labelAJo = Label(frame1, width=4, height=2, text="AJo", relief="groove")
    labelKJo = Label(frame1, width=4, height=2, text="KJo", relief="groove")
    labelQJo = Label(frame1, width=4, height=2, text="QJo", relief="groove")
    labelJJ = Label(frame1, width=4, height=2, text="JJ", relief="groove")
    labelJ10s = Label(frame1, width=4, height=2, text="J10s", relief="groove")
    labelJ9s = Label(frame1, width=4, height=2, text="J9s", relief="groove")
    labelJ8s = Label(frame1, width=4, height=2, text="J8s", relief="groove")
    labelJ7s = Label(frame1, width=4, height=2, text="J7s", relief="groove")
    labelJ6s = Label(frame1, width=4, height=2, text="J6s", relief="groove")
    labelJ5s = Label(frame1, width=4, height=2, text="J5s", relief="groove")
    labelJ4s = Label(frame1, width=4, height=2, text="J4s", relief="groove")
    labelJ3s = Label(frame1, width=4, height=2, text="J3s", relief="groove")
    labelJ2s = Label(frame1, width=4, height=2, text="J2s", relief="groove")

    labe4 = [labelAJo, labelKJo, labelQJo, labelJJ, labelJ10s, labelJ9s, labelJ8s, labelJ7s, labelJ6s, labelJ5s, labelJ4s, labelJ3s, labelJ2s]

    labelA10o = Label(frame1, width=4, height=2, text="A10o", relief="groove")
    labelK10o = Label(frame1, width=4, height=2, text="K10o", relief="groove")
    labelQ10o = Label(frame1, width=4, height=2, text="Q10o", relief="groove")
    labelJ10o = Label(frame1, width=4, height=2, text="J10o", relief="groove")
    label1010 = Label(frame1, width=4, height=2, text="1010", relief="groove")
    label109s = Label(frame1, width=4, height=2, text="109s", relief="groove")
    label108s = Label(frame1, width=4, height=2, text="108s", relief="groove")
    label107s = Label(frame1, width=4, height=2, text="107s", relief="groove")
    label106s = Label(frame1, width=4, height=2, text="106s", relief="groove")
    label105s = Label(frame1, width=4, height=2, text="105s", relief="groove")
    label104s = Label(frame1, width=4, height=2, text="104s", relief="groove")
    label103s = Label(frame1, width=4, height=2, text="103s", relief="groove")
    label102s = Label(frame1, width=4, height=2, text="102s", relief="groove")

    labe5 = [labelA10o, labelK10o, labelQ10o, labelJ10o, label1010, label109s, label108s, label107s, label106s, label105s, label104s, label103s, label102s]

    labelA9o = Label(frame1, width=4, height=2, text="A9o", relief="groove")
    labelK9o = Label(frame1, width=4, height=2, text="K9o", relief="groove")
    labelQ9o = Label(frame1, width=4, height=2, text="Q9o", relief="groove")
    labelJ9o = Label(frame1, width=4, height=2, text="J9o", relief="groove")
    label109o = Label(frame1, width=4, height=2, text="109o", relief="groove")
    label99 = Label(frame1, width=4, height=2, text="99", relief="groove")
    label98s = Label(frame1, width=4, height=2, text="98s", relief="groove")
    label97s = Label(frame1, width=4, height=2, text="97s", relief="groove")
    label96s = Label(frame1, width=4, height=2, text="96s", relief="groove")
    label95s = Label(frame1, width=4, height=2, text="95s", relief="groove")
    label94s = Label(frame1, width=4, height=2, text="94s", relief="groove")
    label93s = Label(frame1, width=4, height=2, text="93s", relief="groove")
    label92s = Label(frame1, width=4, height=2, text="92s", relief="groove")

    labe6 = [labelA9o, labelK9o, labelQ9o, labelJ9o, label109o, label99, label98s, label97s, label96s, label95s, label94s, label93s, label92s]

    labelA8o = Label(frame1, width=4, height=2, text="A8o", relief="groove")
    labelK8o = Label(frame1, width=4, height=2, text="K8o", relief="groove")
    labelQ8o = Label(frame1, width=4, height=2, text="Q8o", relief="groove")
    labelJ8o = Label(frame1, width=4, height=2, text="J8o", relief="groove")
    label108o = Label(frame1, width=4, height=2, text="108o", relief="groove")
    label98o = Label(frame1, width=4, height=2, text="98o", relief="groove")
    label88 = Label(frame1, width=4, height=2, text="88", relief="groove")
    label87s = Label(frame1, width=4, height=2, text="87s", relief="groove")
    label86s = Label(frame1, width=4, height=2, text="86s", relief="groove")
    label85s = Label(frame1, width=4, height=2, text="85s", relief="groove")
    label84s = Label(frame1, width=4, height=2, text="84s", relief="groove")
    label83s = Label(frame1, width=4, height=2, text="83s", relief="groove")
    label82s = Label(frame1, width=4, height=2, text="82s", relief="groove")

    labe7 = [labelA8o, labelK8o, labelQ8o, labelJ8o, label108o, label98o, label88, label87s, label86s, label85s, label84s, label83s, label82s]
    
    labelA7o = Label(frame1, width=4, height=2, text="A7o", relief="groove")
    labelK7o = Label(frame1, width=4, height=2, text="K7o", relief="groove")
    labelQ7o = Label(frame1, width=4, height=2, text="Q7o", relief="groove")
    labelJ7o = Label(frame1, width=4, height=2, text="J7o", relief="groove")
    label107o = Label(frame1, width=4, height=2, text="107o", relief="groove")
    label97o = Label(frame1, width=4, height=2, text="97o", relief="groove")
    label87o = Label(frame1, width=4, height=2, text="87o", relief="groove")
    label77 = Label(frame1, width=4, height=2, text="77", relief="groove")
    label76s = Label(frame1, width=4, height=2, text="76s", relief="groove")
    label75s = Label(frame1, width=4, height=2, text="75s", relief="groove")
    label74s = Label(frame1, width=4, height=2, text="74s", relief="groove")
    label73s = Label(frame1, width=4, height=2, text="73s", relief="groove")
    label72s = Label(frame1, width=4, height=2, text="72s", relief="groove")

    labe8 = [labelA7o, labelK7o, labelQ7o, labelJ7o, label107o, label97o, label87o, label77, label76s, label75s, label74s, label73s, label72s]

    labelA6o = Label(frame1, width=4, height=2, text="A6o", relief="groove")
    labelK6o = Label(frame1, width=4, height=2, text="K6o", relief="groove")
    labelQ6o = Label(frame1, width=4, height=2, text="Q6o", relief="groove")
    labelJ6o = Label(frame1, width=4, height=2, text="J6o", relief="groove")
    label106o = Label(frame1, width=4, height=2, text="106o", relief="groove")
    label96o = Label(frame1, width=4, height=2, text="96o", relief="groove")
    label86o = Label(frame1, width=4, height=2, text="86o", relief="groove")
    label76o = Label(frame1, width=4, height=2, text="76o", relief="groove")
    label66 = Label(frame1, width=4, height=2, text="66", relief="groove")
    label65s = Label(frame1, width=4, height=2, text="65s", relief="groove")
    label64s = Label(frame1, width=4, height=2, text="64s", relief="groove")
    label63s = Label(frame1, width=4, height=2, text="63s", relief="groove")
    label62s = Label(frame1, width=4, height=2, text="62s", relief="groove")

    labe9 = [labelA6o, labelK6o, labelQ6o, labelJ6o, label106o, label96o, label86o, label76o, label66, label65s, label64s, label63s, label62s]

    labelA5o = Label(frame1, width=4, height=2, text="A5o", relief="groove")
    labelK5o = Label(frame1, width=4, height=2, text="K5o", relief="groove")
    labelQ5o = Label(frame1, width=4, height=2, text="Q5o", relief="groove")
    labelJ5o = Label(frame1, width=4, height=2, text="J5o", relief="groove")
    label105o = Label(frame1, width=4, height=2, text="105o", relief="groove")
    label95o = Label(frame1, width=4, height=2, text="95o", relief="groove")
    label85o = Label(frame1, width=4, height=2, text="85o", relief="groove")
    label75o = Label(frame1, width=4, height=2, text="75o", relief="groove")
    label65o = Label(frame1, width=4, height=2, text="65o", relief="groove")
    label55 = Label(frame1, width=4, height=2, text="55", relief="groove")
    label54s = Label(frame1, width=4, height=2, text="54s", relief="groove")
    label53s = Label(frame1, width=4, height=2, text="53s", relief="groove")
    label52s = Label(frame1, width=4, height=2, text="52s", relief="groove")

    labe10 = [labelA5o, labelK5o, labelQ5o, labelJ5o, label105o, label95o, label85o, label75o, label65o, label55, label54s, label53s, label52s]

    labelA4o = Label(frame1, width=4, height=2, text="A4o", relief="groove")
    labelK4o = Label(frame1, width=4, height=2, text="K4o", relief="groove")
    labelQ4o = Label(frame1, width=4, height=2, text="Q4o", relief="groove")
    labelJ4o = Label(frame1, width=4, height=2, text="J4o", relief="groove")
    label104o = Label(frame1, width=4, height=2, text="104o", relief="groove")
    label94o = Label(frame1, width=4, height=2, text="94o", relief="groove")
    label84o = Label(frame1, width=4, height=2, text="84o", relief="groove")
    label74o = Label(frame1, width=4, height=2, text="74o", relief="groove")
    label64o = Label(frame1, width=4, height=2, text="64o", relief="groove")
    label54o = Label(frame1, width=4, height=2, text="54o", relief="groove")
    label44 = Label(frame1, width=4, height=2, text="44", relief="groove")
    label43s = Label(frame1, width=4, height=2, text="43s", relief="groove")
    label42s = Label(frame1, width=4, height=2, text="42s", relief="groove")

    labe11 = [labelA4o, labelK4o, labelQ4o, labelJ4o, label104o, label94o, label84o, label74o, label64o, label54o, label44, label43s, label42s]

    labelA3o = Label(frame1, width=4, height=2, text="A3o", relief="groove")
    labelK3o = Label(frame1, width=4, height=2, text="K3o", relief="groove")
    labelQ3o = Label(frame1, width=4, height=2, text="Q3o", relief="groove")
    labelJ3o = Label(frame1, width=4, height=2, text="J3o", relief="groove")
    label103o = Label(frame1, width=4, height=2, text="103o", relief="groove")
    label93o = Label(frame1, width=4, height=2, text="93o", relief="groove")
    label83o = Label(frame1, width=4, height=2, text="83o", relief="groove")
    label73o = Label(frame1, width=4, height=2, text="73o", relief="groove")
    label63o = Label(frame1, width=4, height=2, text="63o", relief="groove")
    label53o = Label(frame1, width=4, height=2, text="53o", relief="groove")
    label43o = Label(frame1, width=4, height=2, text="43o", relief="groove")
    label33 = Label(frame1, width=4, height=2, text="33", relief="groove")
    label32s = Label(frame1, width=4, height=2, text="32s", relief="groove")

    labe12 = [labelA3o, labelK3o, labelQ3o, labelJ3o, label103o, label93o, label83o, label73o, label63o, label53o, label43o, label33, label32s]

    labelA2o = Label(frame1, width=4, height=2, text="A2o", relief="groove")
    labelK2o = Label(frame1, width=4, height=2, text="K2o", relief="groove")
    labelQ2o = Label(frame1, width=4, height=2, text="Q2o", relief="groove")
    labelJ2o = Label(frame1, width=4, height=2, text="J2o", relief="groove")
    label102o = Label(frame1, width=4, height=2, text="102o", relief="groove")
    label92o = Label(frame1, width=4, height=2, text="92o", relief="groove")
    label82o = Label(frame1, width=4, height=2, text="82o", relief="groove")
    label72o = Label(frame1, width=4, height=2, text="72o", relief="groove")
    label62o = Label(frame1, width=4, height=2, text="62o", relief="groove")
    label52o = Label(frame1, width=4, height=2, text="52o", relief="groove")
    label42o = Label(frame1, width=4, height=2, text="42o", relief="groove")
    label32o = Label(frame1, width=4, height=2, text="32o", relief="groove")
    label22 = Label(frame1, width=4, height=2, text="22", relief="groove")

    labe13 = [labelA2o, labelK2o, labelQ2o, labelJ2o, label102o, label92o, label82o, label72o, label62o, label52o, label42o, label32o, label22]

    mlabe = [labe1, labe2, labe3, labe4, labe5, labe6, labe7, labe8, labe9, labe10, labe11, labe12, labe13]

    for i in mlabe:
        for p in i:
            


    labelAA.grid(row=1,column=1)
    labelAKs.grid(row=1,column=2)
    labelAQs.grid(row=1,column=3)
    labelAJs.grid(row=1,column=4)
    labelA10s.grid(row=1,column=5)
    labelA9s.grid(row=1,column=6)
    labelA8s.grid(row=1,column=7)
    labelA7s.grid(row=1,column=8)
    labelA6s.grid(row=1,column=9)
    labelA5s.grid(row=1,column=10)
    labelA4s.grid(row=1,column=11)
    labelA3s.grid(row=1,column=12)
    labelA2s.grid(row=1,column=13)

    labelAKo.grid(row=2,column=1)
    labelKK.grid(row=2,column=2)
    labelKQs.grid(row=2,column=3)
    labelKJs.grid(row=2,column=4)
    labelK10s.grid(row=2,column=5)
    labelK9s.grid(row=2,column=6)
    labelK8s.grid(row=2,column=7)
    labelK7s.grid(row=2,column=8)
    labelK6s.grid(row=2,column=9)
    labelK5s.grid(row=2,column=10)
    labelK4s.grid(row=2,column=11)
    labelK3s.grid(row=2,column=12)
    labelK2s.grid(row=2,column=13)

    labelAQo.grid(row=3,column=1)
    labelKQo.grid(row=3,column=2)
    labelQQ.grid(row=3,column=3)
    labelQJs.grid(row=3,column=4)
    labelQ10s.grid(row=3,column=5)
    labelQ9s.grid(row=3,column=6)
    labelQ8s.grid(row=3,column=7)
    labelQ7s.grid(row=3,column=8)
    labelQ6s.grid(row=3,column=9)
    labelQ5s.grid(row=3,column=10)
    labelQ4s.grid(row=3,column=11)
    labelQ3s.grid(row=3,column=12)
    labelQ2s.grid(row=3,column=13)

    labelAJo.grid(row=4,column=1)
    labelKJo.grid(row=4,column=2)
    labelQJo.grid(row=4,column=3)
    labelJJ.grid(row=4,column=4)
    labelJ10s.grid(row=4,column=5)
    labelJ9s.grid(row=4,column=6)
    labelJ8s.grid(row=4,column=7)
    labelJ7s.grid(row=4,column=8)
    labelJ6s.grid(row=4,column=9)
    labelJ5s.grid(row=4,column=10)
    labelJ4s.grid(row=4,column=11)
    labelJ3s.grid(row=4,column=12)
    labelJ2s.grid(row=4,column=13)

    labelA10o.grid(row=5,column=1)
    labelK10o.grid(row=5,column=2)
    labelQ10o.grid(row=5,column=3)
    labelJ10o.grid(row=5,column=4)
    label1010.grid(row=5,column=5)
    label109s.grid(row=5,column=6)
    label108s.grid(row=5,column=7)
    label107s.grid(row=5,column=8)
    label106s.grid(row=5,column=9)
    label105s.grid(row=5,column=10)
    label104s.grid(row=5,column=11)
    label103s.grid(row=5,column=12)
    label102s.grid(row=5,column=13)

    labelA9o.grid(row=6,column=1)
    labelK9o.grid(row=6,column=2)
    labelQ9o.grid(row=6,column=3)
    labelJ9o.grid(row=6,column=4)
    label109o.grid(row=6,column=5)
    label99.grid(row=6,column=6)
    label98s.grid(row=6,column=7)
    label97s.grid(row=6,column=8)
    label96s.grid(row=6,column=9)
    label95s.grid(row=6,column=10)
    label94s.grid(row=6,column=11)
    label93s.grid(row=6,column=12)
    label92s.grid(row=6,column=13)

    labelA8o.grid(row=7,column=1)
    labelK8o.grid(row=7,column=2)
    labelQ8o.grid(row=7,column=3)
    labelJ8o.grid(row=7,column=4)
    label108o.grid(row=7,column=5)
    label98o.grid(row=7,column=6)
    label88.grid(row=7,column=7)
    label87s.grid(row=7,column=8)
    label86s.grid(row=7,column=9)
    label85s.grid(row=7,column=10)
    label84s.grid(row=7,column=11)
    label83s.grid(row=7,column=12)
    label82s.grid(row=7,column=13)

    labelA7o.grid(row=8,column=1)
    labelK7o.grid(row=8,column=2)
    labelQ7o.grid(row=8,column=3)
    labelJ7o.grid(row=8,column=4)
    label107o.grid(row=8,column=5)
    label97o.grid(row=8,column=6)
    label87o.grid(row=8,column=7)
    label77.grid(row=8,column=8)
    label76s.grid(row=8,column=9)
    label75s.grid(row=8,column=10)
    label74s.grid(row=8,column=11)
    label73s.grid(row=8,column=12)
    label72s.grid(row=8,column=13)

    labelA6o.grid(row=9,column=1)
    labelK6o.grid(row=9,column=2)
    labelQ6o.grid(row=9,column=3)
    labelJ6o.grid(row=9,column=4)
    label106o.grid(row=9,column=5)
    label96o.grid(row=9,column=6)
    label86o.grid(row=9,column=7)
    label76o.grid(row=9,column=8)
    label66.grid(row=9,column=9)
    label65s.grid(row=9,column=10)
    label64s.grid(row=9,column=11)
    label63s.grid(row=9,column=12)
    label62s.grid(row=9,column=13)

    labelA5o.grid(row=10,column=1)
    labelK5o.grid(row=10,column=2)
    labelQ5o.grid(row=10,column=3)
    labelJ5o.grid(row=10,column=4)
    label105o.grid(row=10,column=5)
    label95o.grid(row=10,column=6)
    label85o.grid(row=10,column=7)
    label75o.grid(row=10,column=8)
    label65o.grid(row=10,column=9)
    label55.grid(row=10,column=10)
    label54s.grid(row=10,column=11)
    label53s.grid(row=10,column=12)
    label52s.grid(row=10,column=13)

    labelA4o.grid(row=11,column=1)
    labelK4o.grid(row=11,column=2)
    labelQ4o.grid(row=11,column=3)
    labelJ4o.grid(row=11,column=4)
    label104o.grid(row=11,column=5)
    label94o.grid(row=11,column=6)
    label84o.grid(row=11,column=7)
    label74o.grid(row=11,column=8)
    label64o.grid(row=11,column=9)
    label54o.grid(row=11,column=10)
    label44.grid(row=11,column=11)
    label43s.grid(row=11,column=12)
    label42s.grid(row=11,column=13)

    labelA3o.grid(row=12,column=1)
    labelK3o.grid(row=12,column=2)
    labelQ3o.grid(row=12,column=3)
    labelJ3o.grid(row=12,column=4)
    label103o.grid(row=12,column=5)
    label93o.grid(row=12,column=6)
    label83o.grid(row=12,column=7)
    label73o.grid(row=12,column=8)
    label63o.grid(row=12,column=9)
    label53o.grid(row=12,column=10)
    label43o.grid(row=12,column=11)
    label33.grid(row=12,column=12)
    label32s.grid(row=12,column=13)

    labelA2o.grid(row=13,column=1)
    labelK2o.grid(row=13,column=2)
    labelQ2o.grid(row=13,column=3)
    labelJ2o.grid(row=13,column=4)
    label102o.grid(row=13,column=5)
    label92o.grid(row=13,column=6)
    label82o.grid(row=13,column=7)
    label72o.grid(row=13,column=8)
    label62o.grid(row=13,column=9)
    label52o.grid(row=13,column=10)
    label42o.grid(row=13,column=11)
    label32o.grid(row=13,column=12)
    label22.grid(row=13,column=13)




    labelAA = Label(frame2, width=4, height=2, text="AA", relief="groove")
    labelAKs = Label(frame2, width=4, height=2, text="AKs", relief="groove")
    labelAQs = Label(frame2, width=4, height=2, text="AQs", relief="groove")
    labelAJs = Label(frame2, width=4, height=2, text="AJs", relief="groove")
    labelA10s = Label(frame2, width=4, height=2, text="A10s", relief="groove")
    labelA9s = Label(frame2, width=4, height=2, text="A9s", relief="groove")
    labelA8s = Label(frame2, width=4, height=2, text="A8s", relief="groove")
    labelA7s = Label(frame2, width=4, height=2, text="A7s", relief="groove")
    labelA6s = Label(frame2, width=4, height=2, text="A6s", relief="groove")
    labelA5s = Label(frame2, width=4, height=2, text="A5s", relief="groove")
    labelA4s = Label(frame2, width=4, height=2, text="A4s", relief="groove")
    labelA3s = Label(frame2, width=4, height=2, text="A3s", relief="groove")
    labelA2s = Label(frame2, width=4, height=2, text="A2s", relief="groove")

    labelAKo = Label(frame2, width=4, height=2, text="AKo", relief="groove")
    labelKK = Label(frame2, width=4, height=2, text="KK", relief="groove")
    labelKQs = Label(frame2, width=4, height=2, text="KQs", relief="groove")
    labelKJs = Label(frame2, width=4, height=2, text="KJs", relief="groove")
    labelK10s = Label(frame2, width=4, height=2, text="K10s", relief="groove")
    labelK9s = Label(frame2, width=4, height=2, text="K9s", relief="groove")
    labelK8s = Label(frame2, width=4, height=2, text="K8s", relief="groove")
    labelK7s = Label(frame2, width=4, height=2, text="K7s", relief="groove")
    labelK6s = Label(frame2, width=4, height=2, text="K6s", relief="groove")
    labelK5s = Label(frame2, width=4, height=2, text="K5s", relief="groove")
    labelK4s = Label(frame2, width=4, height=2, text="K4s", relief="groove")
    labelK3s = Label(frame2, width=4, height=2, text="K3s", relief="groove")
    labelK2s = Label(frame2, width=4, height=2, text="K2s", relief="groove")

    labelAQo = Label(frame2, width=4, height=2, text="AQo", relief="groove")
    labelKQo = Label(frame2, width=4, height=2, text="KQo", relief="groove")
    labelQQ = Label(frame2, width=4, height=2, text="QQ", relief="groove")
    labelQJs = Label(frame2, width=4, height=2, text="QJs", relief="groove")
    labelQ10s = Label(frame2, width=4, height=2, text="Q10s", relief="groove")
    labelQ9s = Label(frame2, width=4, height=2, text="Q9s", relief="groove")
    labelQ8s = Label(frame2, width=4, height=2, text="Q8s", relief="groove")
    labelQ7s = Label(frame2, width=4, height=2, text="Q7s", relief="groove")
    labelQ6s = Label(frame2, width=4, height=2, text="Q6s", relief="groove")
    labelQ5s = Label(frame2, width=4, height=2, text="Q5s", relief="groove")
    labelQ4s = Label(frame2, width=4, height=2, text="Q4s", relief="groove")
    labelQ3s = Label(frame2, width=4, height=2, text="Q3s", relief="groove")
    labelQ2s = Label(frame2, width=4, height=2, text="Q2s", relief="groove")

    labelAJo = Label(frame2, width=4, height=2, text="AJo", relief="groove")
    labelKJo = Label(frame2, width=4, height=2, text="KJo", relief="groove")
    labelQJo = Label(frame2, width=4, height=2, text="QJo", relief="groove")
    labelJJ = Label(frame2, width=4, height=2, text="JJ", relief="groove")
    labelJ10s = Label(frame2, width=4, height=2, text="J10s", relief="groove")
    labelJ9s = Label(frame2, width=4, height=2, text="J9s", relief="groove")
    labelJ8s = Label(frame2, width=4, height=2, text="J8s", relief="groove")
    labelJ7s = Label(frame2, width=4, height=2, text="J7s", relief="groove")
    labelJ6s = Label(frame2, width=4, height=2, text="J6s", relief="groove")
    labelJ5s = Label(frame2, width=4, height=2, text="J5s", relief="groove")
    labelJ4s = Label(frame2, width=4, height=2, text="J4s", relief="groove")
    labelJ3s = Label(frame2, width=4, height=2, text="J3s", relief="groove")
    labelJ2s = Label(frame2, width=4, height=2, text="J2s", relief="groove")

    labelA10o = Label(frame2, width=4, height=2, text="A10o", relief="groove")
    labelK10o = Label(frame2, width=4, height=2, text="K10o", relief="groove")
    labelQ10o = Label(frame2, width=4, height=2, text="Q10o", relief="groove")
    labelJ10o = Label(frame2, width=4, height=2, text="J10o", relief="groove")
    label1010 = Label(frame2, width=4, height=2, text="1010", relief="groove")
    label109s = Label(frame2, width=4, height=2, text="109s", relief="groove")
    label108s = Label(frame2, width=4, height=2, text="108s", relief="groove")
    label107s = Label(frame2, width=4, height=2, text="107s", relief="groove")
    label106s = Label(frame2, width=4, height=2, text="106s", relief="groove")
    label105s = Label(frame2, width=4, height=2, text="105s", relief="groove")
    label104s = Label(frame2, width=4, height=2, text="104s", relief="groove")
    label103s = Label(frame2, width=4, height=2, text="103s", relief="groove")
    label102s = Label(frame2, width=4, height=2, text="102s", relief="groove")

    labelA9o = Label(frame2, width=4, height=2, text="A9o", relief="groove")
    labelK9o = Label(frame2, width=4, height=2, text="K9o", relief="groove")
    labelQ9o = Label(frame2, width=4, height=2, text="Q9o", relief="groove")
    labelJ9o = Label(frame2, width=4, height=2, text="J9o", relief="groove")
    label109o = Label(frame2, width=4, height=2, text="109o", relief="groove")
    label99 = Label(frame2, width=4, height=2, text="99", relief="groove")
    label98s = Label(frame2, width=4, height=2, text="98s", relief="groove")
    label97s = Label(frame2, width=4, height=2, text="97s", relief="groove")
    label96s = Label(frame2, width=4, height=2, text="96s", relief="groove")
    label95s = Label(frame2, width=4, height=2, text="95s", relief="groove")
    label94s = Label(frame2, width=4, height=2, text="94s", relief="groove")
    label93s = Label(frame2, width=4, height=2, text="93s", relief="groove")
    label92s = Label(frame2, width=4, height=2, text="92s", relief="groove")

    labelA8o = Label(frame2, width=4, height=2, text="A8o", relief="groove")
    labelK8o = Label(frame2, width=4, height=2, text="K8o", relief="groove")
    labelQ8o = Label(frame2, width=4, height=2, text="Q8o", relief="groove")
    labelJ8o = Label(frame2, width=4, height=2, text="J8o", relief="groove")
    label108o = Label(frame2, width=4, height=2, text="108o", relief="groove")
    label98o = Label(frame2, width=4, height=2, text="98o", relief="groove")
    label88 = Label(frame2, width=4, height=2, text="88", relief="groove")
    label87s = Label(frame2, width=4, height=2, text="87s", relief="groove")
    label86s = Label(frame2, width=4, height=2, text="86s", relief="groove")
    label85s = Label(frame2, width=4, height=2, text="85s", relief="groove")
    label84s = Label(frame2, width=4, height=2, text="84s", relief="groove")
    label83s = Label(frame2, width=4, height=2, text="83s", relief="groove")
    label82s = Label(frame2, width=4, height=2, text="82s", relief="groove")
    
    labelA7o = Label(frame2, width=4, height=2, text="A7o", relief="groove")
    labelK7o = Label(frame2, width=4, height=2, text="K7o", relief="groove")
    labelQ7o = Label(frame2, width=4, height=2, text="Q7o", relief="groove")
    labelJ7o = Label(frame2, width=4, height=2, text="J7o", relief="groove")
    label107o = Label(frame2, width=4, height=2, text="107o", relief="groove")
    label97o = Label(frame2, width=4, height=2, text="97o", relief="groove")
    label87o = Label(frame2, width=4, height=2, text="87o", relief="groove")
    label77 = Label(frame2, width=4, height=2, text="77", relief="groove")
    label76s = Label(frame2, width=4, height=2, text="76s", relief="groove")
    label75s = Label(frame2, width=4, height=2, text="75s", relief="groove")
    label74s = Label(frame2, width=4, height=2, text="74s", relief="groove")
    label73s = Label(frame2, width=4, height=2, text="73s", relief="groove")
    label72s = Label(frame2, width=4, height=2, text="72s", relief="groove")

    labelA6o = Label(frame2, width=4, height=2, text="A6o", relief="groove")
    labelK6o = Label(frame2, width=4, height=2, text="K6o", relief="groove")
    labelQ6o = Label(frame2, width=4, height=2, text="Q6o", relief="groove")
    labelJ6o = Label(frame2, width=4, height=2, text="J6o", relief="groove")
    label106o = Label(frame2, width=4, height=2, text="106o", relief="groove")
    label96o = Label(frame2, width=4, height=2, text="96o", relief="groove")
    label86o = Label(frame2, width=4, height=2, text="86o", relief="groove")
    label76o = Label(frame2, width=4, height=2, text="76o", relief="groove")
    label66 = Label(frame2, width=4, height=2, text="66", relief="groove")
    label65s = Label(frame2, width=4, height=2, text="65s", relief="groove")
    label64s = Label(frame2, width=4, height=2, text="64s", relief="groove")
    label63s = Label(frame2, width=4, height=2, text="63s", relief="groove")
    label62s = Label(frame2, width=4, height=2, text="62s", relief="groove")

    labelA5o = Label(frame2, width=4, height=2, text="A5o", relief="groove")
    labelK5o = Label(frame2, width=4, height=2, text="K5o", relief="groove")
    labelQ5o = Label(frame2, width=4, height=2, text="Q5o", relief="groove")
    labelJ5o = Label(frame2, width=4, height=2, text="J5o", relief="groove")
    label105o = Label(frame2, width=4, height=2, text="105o", relief="groove")
    label95o = Label(frame2, width=4, height=2, text="95o", relief="groove")
    label85o = Label(frame2, width=4, height=2, text="85o", relief="groove")
    label75o = Label(frame2, width=4, height=2, text="75o", relief="groove")
    label65o = Label(frame2, width=4, height=2, text="65o", relief="groove")
    label55 = Label(frame2, width=4, height=2, text="55", relief="groove")
    label54s = Label(frame2, width=4, height=2, text="54s", relief="groove")
    label53s = Label(frame2, width=4, height=2, text="53s", relief="groove")
    label52s = Label(frame2, width=4, height=2, text="52s", relief="groove")

    labelA4o = Label(frame2, width=4, height=2, text="A4o", relief="groove")
    labelK4o = Label(frame2, width=4, height=2, text="K4o", relief="groove")
    labelQ4o = Label(frame2, width=4, height=2, text="Q4o", relief="groove")
    labelJ4o = Label(frame2, width=4, height=2, text="J4o", relief="groove")
    label104o = Label(frame2, width=4, height=2, text="104o", relief="groove")
    label94o = Label(frame2, width=4, height=2, text="94o", relief="groove")
    label84o = Label(frame2, width=4, height=2, text="84o", relief="groove")
    label74o = Label(frame2, width=4, height=2, text="74o", relief="groove")
    label64o = Label(frame2, width=4, height=2, text="64o", relief="groove")
    label54o = Label(frame2, width=4, height=2, text="54o", relief="groove")
    label44 = Label(frame2, width=4, height=2, text="44", relief="groove")
    label43s = Label(frame2, width=4, height=2, text="43s", relief="groove")
    label42s = Label(frame2, width=4, height=2, text="42s", relief="groove")

    labelA3o = Label(frame2, width=4, height=2, text="A3o", relief="groove")
    labelK3o = Label(frame2, width=4, height=2, text="K3o", relief="groove")
    labelQ3o = Label(frame2, width=4, height=2, text="Q3o", relief="groove")
    labelJ3o = Label(frame2, width=4, height=2, text="J3o", relief="groove")
    label103o = Label(frame2, width=4, height=2, text="103o", relief="groove")
    label93o = Label(frame2, width=4, height=2, text="93o", relief="groove")
    label83o = Label(frame2, width=4, height=2, text="83o", relief="groove")
    label73o = Label(frame2, width=4, height=2, text="73o", relief="groove")
    label63o = Label(frame2, width=4, height=2, text="63o", relief="groove")
    label53o = Label(frame2, width=4, height=2, text="53o", relief="groove")
    label43o = Label(frame2, width=4, height=2, text="43o", relief="groove")
    label33 = Label(frame2, width=4, height=2, text="33", relief="groove")
    label32s = Label(frame2, width=4, height=2, text="32s", relief="groove")

    labelA2o = Label(frame2, width=4, height=2, text="A2o", relief="groove")
    labelK2o = Label(frame2, width=4, height=2, text="K2o", relief="groove")
    labelQ2o = Label(frame2, width=4, height=2, text="Q2o", relief="groove")
    labelJ2o = Label(frame2, width=4, height=2, text="J2o", relief="groove")
    label102o = Label(frame2, width=4, height=2, text="102o", relief="groove")
    label92o = Label(frame2, width=4, height=2, text="92o", relief="groove")
    label82o = Label(frame2, width=4, height=2, text="82o", relief="groove")
    label72o = Label(frame2, width=4, height=2, text="72o", relief="groove")
    label62o = Label(frame2, width=4, height=2, text="62o", relief="groove")
    label52o = Label(frame2, width=4, height=2, text="52o", relief="groove")
    label42o = Label(frame2, width=4, height=2, text="42o", relief="groove")
    label32o = Label(frame2, width=4, height=2, text="32o", relief="groove")
    label22 = Label(frame2, width=4, height=2, text="22", relief="groove")


    labelAA.grid(row=1,column=1)
    labelAKs.grid(row=1,column=2)
    labelAQs.grid(row=1,column=3)
    labelAJs.grid(row=1,column=4)
    labelA10s.grid(row=1,column=5)
    labelA9s.grid(row=1,column=6)
    labelA8s.grid(row=1,column=7)
    labelA7s.grid(row=1,column=8)
    labelA6s.grid(row=1,column=9)
    labelA5s.grid(row=1,column=10)
    labelA4s.grid(row=1,column=11)
    labelA3s.grid(row=1,column=12)
    labelA2s.grid(row=1,column=13)

    labelAKo.grid(row=2,column=1)
    labelKK.grid(row=2,column=2)
    labelKQs.grid(row=2,column=3)
    labelKJs.grid(row=2,column=4)
    labelK10s.grid(row=2,column=5)
    labelK9s.grid(row=2,column=6)
    labelK8s.grid(row=2,column=7)
    labelK7s.grid(row=2,column=8)
    labelK6s.grid(row=2,column=9)
    labelK5s.grid(row=2,column=10)
    labelK4s.grid(row=2,column=11)
    labelK3s.grid(row=2,column=12)
    labelK2s.grid(row=2,column=13)

    labelAQo.grid(row=3,column=1)
    labelKQo.grid(row=3,column=2)
    labelQQ.grid(row=3,column=3)
    labelQJs.grid(row=3,column=4)
    labelQ10s.grid(row=3,column=5)
    labelQ9s.grid(row=3,column=6)
    labelQ8s.grid(row=3,column=7)
    labelQ7s.grid(row=3,column=8)
    labelQ6s.grid(row=3,column=9)
    labelQ5s.grid(row=3,column=10)
    labelQ4s.grid(row=3,column=11)
    labelQ3s.grid(row=3,column=12)
    labelQ2s.grid(row=3,column=13)

    labelAJo.grid(row=4,column=1)
    labelKJo.grid(row=4,column=2)
    labelQJo.grid(row=4,column=3)
    labelJJ.grid(row=4,column=4)
    labelJ10s.grid(row=4,column=5)
    labelJ9s.grid(row=4,column=6)
    labelJ8s.grid(row=4,column=7)
    labelJ7s.grid(row=4,column=8)
    labelJ6s.grid(row=4,column=9)
    labelJ5s.grid(row=4,column=10)
    labelJ4s.grid(row=4,column=11)
    labelJ3s.grid(row=4,column=12)
    labelJ2s.grid(row=4,column=13)

    labelA10o.grid(row=5,column=1)
    labelK10o.grid(row=5,column=2)
    labelQ10o.grid(row=5,column=3)
    labelJ10o.grid(row=5,column=4)
    label1010.grid(row=5,column=5)
    label109s.grid(row=5,column=6)
    label108s.grid(row=5,column=7)
    label107s.grid(row=5,column=8)
    label106s.grid(row=5,column=9)
    label105s.grid(row=5,column=10)
    label104s.grid(row=5,column=11)
    label103s.grid(row=5,column=12)
    label102s.grid(row=5,column=13)

    labelA9o.grid(row=6,column=1)
    labelK9o.grid(row=6,column=2)
    labelQ9o.grid(row=6,column=3)
    labelJ9o.grid(row=6,column=4)
    label109o.grid(row=6,column=5)
    label99.grid(row=6,column=6)
    label98s.grid(row=6,column=7)
    label97s.grid(row=6,column=8)
    label96s.grid(row=6,column=9)
    label95s.grid(row=6,column=10)
    label94s.grid(row=6,column=11)
    label93s.grid(row=6,column=12)
    label92s.grid(row=6,column=13)

    labelA8o.grid(row=7,column=1)
    labelK8o.grid(row=7,column=2)
    labelQ8o.grid(row=7,column=3)
    labelJ8o.grid(row=7,column=4)
    label108o.grid(row=7,column=5)
    label98o.grid(row=7,column=6)
    label88.grid(row=7,column=7)
    label87s.grid(row=7,column=8)
    label86s.grid(row=7,column=9)
    label85s.grid(row=7,column=10)
    label84s.grid(row=7,column=11)
    label83s.grid(row=7,column=12)
    label82s.grid(row=7,column=13)

    labelA7o.grid(row=8,column=1)
    labelK7o.grid(row=8,column=2)
    labelQ7o.grid(row=8,column=3)
    labelJ7o.grid(row=8,column=4)
    label107o.grid(row=8,column=5)
    label97o.grid(row=8,column=6)
    label87o.grid(row=8,column=7)
    label77.grid(row=8,column=8)
    label76s.grid(row=8,column=9)
    label75s.grid(row=8,column=10)
    label74s.grid(row=8,column=11)
    label73s.grid(row=8,column=12)
    label72s.grid(row=8,column=13)

    labelA6o.grid(row=9,column=1)
    labelK6o.grid(row=9,column=2)
    labelQ6o.grid(row=9,column=3)
    labelJ6o.grid(row=9,column=4)
    label106o.grid(row=9,column=5)
    label96o.grid(row=9,column=6)
    label86o.grid(row=9,column=7)
    label76o.grid(row=9,column=8)
    label66.grid(row=9,column=9)
    label65s.grid(row=9,column=10)
    label64s.grid(row=9,column=11)
    label63s.grid(row=9,column=12)
    label62s.grid(row=9,column=13)

    labelA5o.grid(row=10,column=1)
    labelK5o.grid(row=10,column=2)
    labelQ5o.grid(row=10,column=3)
    labelJ5o.grid(row=10,column=4)
    label105o.grid(row=10,column=5)
    label95o.grid(row=10,column=6)
    label85o.grid(row=10,column=7)
    label75o.grid(row=10,column=8)
    label65o.grid(row=10,column=9)
    label55.grid(row=10,column=10)
    label54s.grid(row=10,column=11)
    label53s.grid(row=10,column=12)
    label52s.grid(row=10,column=13)

    labelA4o.grid(row=11,column=1)
    labelK4o.grid(row=11,column=2)
    labelQ4o.grid(row=11,column=3)
    labelJ4o.grid(row=11,column=4)
    label104o.grid(row=11,column=5)
    label94o.grid(row=11,column=6)
    label84o.grid(row=11,column=7)
    label74o.grid(row=11,column=8)
    label64o.grid(row=11,column=9)
    label54o.grid(row=11,column=10)
    label44.grid(row=11,column=11)
    label43s.grid(row=11,column=12)
    label42s.grid(row=11,column=13)

    labelA3o.grid(row=12,column=1)
    labelK3o.grid(row=12,column=2)
    labelQ3o.grid(row=12,column=3)
    labelJ3o.grid(row=12,column=4)
    label103o.grid(row=12,column=5)
    label93o.grid(row=12,column=6)
    label83o.grid(row=12,column=7)
    label73o.grid(row=12,column=8)
    label63o.grid(row=12,column=9)
    label53o.grid(row=12,column=10)
    label43o.grid(row=12,column=11)
    label33.grid(row=12,column=12)
    label32s.grid(row=12,column=13)

    labelA2o.grid(row=13,column=1)
    labelK2o.grid(row=13,column=2)
    labelQ2o.grid(row=13,column=3)
    labelJ2o.grid(row=13,column=4)
    label102o.grid(row=13,column=5)
    label92o.grid(row=13,column=6)
    label82o.grid(row=13,column=7)
    label72o.grid(row=13,column=8)
    label62o.grid(row=13,column=9)
    label52o.grid(row=13,column=10)
    label42o.grid(row=13,column=11)
    label32o.grid(row=13,column=12)
    label22.grid(row=13,column=13)


    





    exploiter.mainloop()




def testhi():
    select2 = Tk()
    select2.title("Hi")
    select2.geometry("300x200-1300+600")
    select2.resizable(False,False)

    select2.mainloop()


def select_style():
    select1 = Tk()
    select1.title("Poker Learning Tools")
    select1.geometry("300x200-1300+600")
    select1.resizable(False,False)

    button_cs = Button(select1, width=15, text="Calling Staion", overrelief="solid", command=strategy)
    button_cs.pack()
    button_ma = Button(select1, width=15, text="Manic", overrelief="solid", command=strategy)
    button_ma.pack()

    select1.mainloop()



root = Tk()

root.title("Poker Learning Tools")
root.geometry("300x200-1300+600")
root.resizable(False,False)

button1 = Button(root, width=15, text="Learn Strategy", overrelief="solid", command=select_style)
button1.pack()
button2 = Button(root, width=15, text="VS AI", overrelief="solid")
button2.pack()




root.mainloop()